import '../scss/main.scss';
import Header from "./components/Header/Header"
import Footer from './components/Footer/Footer';
export const metadata = {
  title: 'MNTN',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
