import boys from '../../../images/blog/hiking/boys.jpg';
import couple from '../../../images/blog/hiking/couple.jpg';
import hiking from '../../../images/blog/hiking/hiking.jpg';
import tourists from '../../../images/blog/hiking/tourists.jpg';

const hikingAtricles = [
    {
        "id": "12345",
        "title": "How to Choose and Use Trekking Poles and Hiking Staffs",
        "article": "Trekking poles and hiking staffs are standard equipment for many walkers, hikers, trekkers, backpackers and snowshoers. The reasons why are simple: They enhance your stability and provide support on all types of terrain. Types of Trekking Poles. Trekking Poles: Sold as a pair and used in tandem, trekking poles enhance your stability and can reduce force on your knees while hiking and backpacking. Most are adjustable in length and some include internal springs that absorb shock to further reduce impact. Hiking Staff: Sometimes called a walking staff or travel staff, this is a single pole that's most effective when used on relatively flat terrain and with little or no load on your back. Hiking staffs are adjustable and some include a shock-absorbing feature. They may also include a built-in camera mount under the handle so the staff can be used as a monopod. Some trekking poles are marketed specifically for men, women and kids, but the majority are considered unisex. The primary things that differ among men’s, women’s and kids’ poles are length, weight, grip size and color. In the end, buy whichever poles fit you best and have the colors and features you want.",
        "image": boys,
    },
    {
        "id": "456",
        "title": "Day Hiking Essentials Checklist",
        "article": "While you’re packing, use these handy day hiking checklists to make sure you don’t forget anything important. Here are some notes on how to best use the lists: The Ten Essentials: Items that are part of the Ten Essentials are marked by an asterisk (*). The exact items you take can be tailored to your trip based on considerations such as weather, difficulty, duration and distance from help. To learn more, see our article on the Ten Essentials.These checklists are guidelines. They are deliberately comprehensive; your needs may vary. Adapt them to suit your hike as necessary. Printer-friendly PDFs. Print out the PDF version of each checklist for easy reference while packing. If you’re someone who likes to physically tick items off your list, consider laminating the checklists. Then use a dry erase marker to mark them up. These items should always be on your hiking checklist: Hiking pack,Weather-appropriate clothing (think moisture-wicking and layers),Hiking footwear,Plenty of food,Plenty of water,Navigation tools such as a map and compass,First-aid kit,Knife or multi-tool,The rest of the Ten Essentials as appropriate for your hike",
        "image": couple,
    },
    {
        "id": "123457", "title": "How to Set Up a Tent", "article": "Before you hit the trail, set your tent up at home: Home offers a low-stress environment for you to master the pitching process for a new tent. The worst time for learning is after you’ve finished a long day of hiking, the sun has set and the rain is coming down sideways. Read the instructions carefully and inventory the parts: Reading instructions, rather than grabbing things and winging it, is a great way to prevent confusion and damage to tent parts. And if a piece is missing, you’ve built in the time to get it before your trip. And don’t forget to pack along a copy of the instructions. Decide on your footprint strategy: Though tent floors are heavy duty to stand up to water, abrasion and wear, the ground is a formidable foe. You can combat this problem by buying a footprint—a custom-sized ground sheet that offers an extra layer of protection. You can also buy Tyvek® material to make your own footprint or you can simply buy a tarp. Footprints are sized smaller than your tent floor so they don’t catch and pool rainwater under your tent. If you make your own footprint, do the same. If you bring a full tarp, fold it under so that no part extends beyond the floor perimeter. Clear debris from your tent site: Your goal is to protect the tent floor and remove things that can poke you in the backside. This isn’t an excavation project, though: Pick another site if you feel like yours needs major work.If it’s windy, stake down tent corners: A strong wind can make laying out your tent feel more like flying a kite. Quickly stake down the corners at the outset; it’s a simple task to restake your tent in its final position later. Go slow with the poles: During setup, poles can get tweaked or chipped, so take a few extra moments to unfurl and seat each pole section with care.Stakeout tactics: You'll get maximum holding power in most types of soil if the stake is fully vertical as you drive it into the ground. Leave just enough stake exposed to allow you to slip a tie-down cord over it. If you can't push the stake in with your hand or foot, you can use a large rock for this job; you can also pack a special stake hammer.Pack extra stakes in case some hidden rock pretzels one of yours. Consider packing sand anchors or snow stakes for those environments.", "image": tourists,
    },
    { "id": "12348", "title": "Understanding Sleeping Bag Temperature Ratings", "article": "Because waking up in your tent shivering in the middle of the night is a miserable experience, the key factor when you choose a sleeping bag is its temperature rating. If you have a reasonable idea of the coldest conditions you anticipate on your adventure, you can pick a bag that will keep you warm at or below that temperature.Sleeping bag temperature ratings, however, are a somewhat complicated subject. To understand them better, it helps to understand how the bags are tested for warmth in the lab (including some of the limitations in the process), and the meaning of some not-so-intuitive terms you’ll see in bag temperature ratings. Here are important things to understand when using temperature ratings to shop for a sleeping bag:Lab-tested temperature ratings (as indicated by “EN” or “ISO” ratings) are useful for making an apples-to-apples comparison between sleeping bags from different brands. Real-world comfort probably won’t match lab-tested temperature ratings because of all the variables that a lab can’t simulate. How Sleeping Bags are Tested In the old days, brands tested sleeping bags in their own labs using a variety of methods, so there was no way to know if one company’s 30-degree bag was truly just as warm as another’s 30-degree bag. The bag industry solved this problem by agreeing to test bags the same way for all brands. Today most brands send their sleeping bags to an independent test lab that assigns bag temperature ratings.EN (European Norm), was the original standard adopted by the sleeping bag industry. Today, a new entity, the ISO (International Standards Organization), oversees bag testing, but the method is almost identical to the EN bag test. (Because ISO testing is so similar to EN testing, you can compare your old EN-rated bag to a newer bag that sports an ISO temperature rating when you shop.)", "image": hiking, }
]

export default hikingAtricles;