import happiness from '../../../images/blog/happiness.jpg';
import things from '../../../images/blog/things.jpg';
import girls from '../../../images/blog/girls.jpg';
import group from '../../../images/blog/group.jpg';
import boys from '../../../images/blog/hiking/boys.jpg';
import couple from '../../../images/blog/hiking/couple.jpg';
import hiking from '../../../images/blog/hiking/hiking.jpg';
import tourists from '../../../images/blog/hiking/tourists.jpg';

const campingArticles = [
    {
        "id": "12345",
        "title": "How to Choose Tents for Camping",
        "article": "Car camping with family or friends is a summer pastime for many of us. Whether the campground itself is the main attraction or it's simply your base camp for nearby activities, this article will help you find the right camping tent—your home away from home.Tent Sleeping Capacity When choosing your tent, first choose a model based on your group's size and whether or not you might need additional space for extra friends, gear or dogs. Keep in mind, however, that no industry standard exists that defines per-person tent dimensions. When evaluating tent capacity ratings, our general advice is this: Assume a close fit. If you seek more room, consider upsizing your tent capacity by 1 person, particularly if you or your usual tent companion(s): -are large people -are claustrophobic -toss and turn at night -sleep better with more than average elbow room -are bringing a small child or a dog. Tents Seasonality: 3-Season Tents By far the most popular choice of tents, 3-season tents are lightweight shelters designed for the relatively temperate conditions of spring, summer and fall. They are usually equipped with ample mesh panels to boost air flow. Mesh panels keep out insects (but can still let in powdery blowing sand). Properly pitched with a taut rainfly, 3-season tents can withstand downpours but are not the best choice for sustained exposure to harsh storms, violent winds or heavy snow. The primary functions of 3-season tents: Keep you dry during rain or light snow. Shield you from bugs. Provide privacy. 3- 4-Season Tents Extended-season (3+ season) tents are engineered for prolonged 3-season usage, suitable for summer use but also trips in early spring and late fall when moderate snow may be encountered. Their goal: offer a balance of ventilation, strength and warmth-retention.  Typically they include 1 or 2 more poles and fewer mesh panels than pure 3-season models. This makes them sturdier and warmer than their 3-season cousins. Extended-season tents are a good choice for those who make frequent trips to exposed, high-elevation destinations. While very sturdy, they are not as fully fortified for harsh winter weather as 4-season tents. 4-Season Tents Engineered to withstand fierce winds and substantial snow loads, mountaineering tents can be used in any season. Their chief function, though, is to stand firm in the face of seriously inhospitable weather, principally in winter or above treeline.",
        "image": happiness,
    },
    {
        "id": "123456", "title": "How to Go Camping",
        "article": "If you haven’t been camping since childhood or have never camped out before, we can help. We keep things simple for your first trip, talk a little about tents and sleeping bags, and show you how to build a great campfire. All that, plus we give you a printable checklist full of stuff you might want for future trips.Even if you’re the most urban of creatures, the urge to get out of the city—to camp out, in fact—can seize your imagination at any time. If you find yourself contemplating car camping for the first time, but also find the gear and the prep to be a little daunting, don’t despair. We’re here to help. The ultimate essential for beginner campers is, of course, an experienced outdoorsy person to help you. You can find those folks teaching classes at REI. And if you’re lucky enough to have a friend with a campground reservation and a garage full of gear to share, then simply jump ahead to our handy, printable checklist of camping essentials we’ve provided at the tail end of story. But you can also do this camping thing completely on your own. You just need a few basic pieces of gear and then decide where you’re going. When going car camping for the first time, start with an overnight campout and keep it simple: To save money, borrow or rent big-ticket gear.To maximize your comfort, always bring appropriate clothes for cold and rain. To satisfy your fresh-air-fueled hunger, bring plenty of food. To keep your options open, camp close to home. (There’s no shame in bailing if problems arise.) To ensure you get a good first impression, postpone your campout if the weather forecast is awful. To be sure you leave a good impression for those who come after you, make sure you follow Leave No Trace principles.",
        "image": group,
    },
    { "id": "123457", "title": "Where to Go Camping", "article": "From national parks to RV parks, the possibilities are endless. Humanity’s enthusiasm for camping is also endless, though, so make your campground reservations well in advance. Where Can I Camp goes into detail about places that offer camping and guidelines that apply in those lands. Recreation.gov is an online site that covers public lands campsite reservations nationwide. Hipcamp is a great resource for finding and reserving private lands campsites nationwide (and worldwide).Another option is campgrounds that are open on a first-come, first-served basis. Booking months ahead isn’t required, but it’s a good idea to check with the campground to get tips on the best time to show up in order to snag a site. Unless you want to get in touch with your inner feral animal, avoid dispersed camping (no facilities) and primitive sites (pit toilets). Most first-time campers are more comfortable in a developed campground, so look for one with flush toilets and running water. It’s also worth verifying that you have treated water coming out of a spigot. Natural water sources introduce the added complexity of water treatment to avoid health risks.", "image": girls, },
    { "id": "12348", "title": "Camping Checklist", "article": "Camping is a great way to get outside with family and friends or even by yourself. You can go camping in many state and national parks, at private campgrounds, in the backcountry or even in your own backyard. (For more info, read Where Can I Camp?) Most campsites include a picnic table, a place to park your car and a spot to pitch your tent. Many also have shared bathrooms and running water. Part of the joy of camping is needing very little gear to exist outdoors. But it’s also nice to have a comfortable, convenient and homey campsite. If it’s your first time camping, it might be best to borrow or rent some of these things. As you become a more experienced camper, you may find that part of the fun is figuring out what to bring along to meet your needs. While you’re packing, use this handy camping checklist to make sure you don’t forget anything important and make sure to stock up on the things you need. This is a comprehensive list, and we don't expect you to bring along every item — though we won't judge you if you do!", "image": things, },
    {
        "id": "12345",
        "title": "How to Choose and Use Trekking Poles and Hiking Staffs",
        "article": "Trekking poles and hiking staffs are standard equipment for many walkers, hikers, trekkers, backpackers and snowshoers. The reasons why are simple: They enhance your stability and provide support on all types of terrain. Types of Trekking Poles. Trekking Poles: Sold as a pair and used in tandem, trekking poles enhance your stability and can reduce force on your knees while hiking and backpacking. Most are adjustable in length and some include internal springs that absorb shock to further reduce impact. Hiking Staff: Sometimes called a walking staff or travel staff, this is a single pole that's most effective when used on relatively flat terrain and with little or no load on your back. Hiking staffs are adjustable and some include a shock-absorbing feature. They may also include a built-in camera mount under the handle so the staff can be used as a monopod. Some trekking poles are marketed specifically for men, women and kids, but the majority are considered unisex. The primary things that differ among men’s, women’s and kids’ poles are length, weight, grip size and color. In the end, buy whichever poles fit you best and have the colors and features you want.",
        "image": boys,
    },
    {
        "id": "456",
        "title": "Day Hiking Essentials Checklist",
        "article": "While you’re packing, use these handy day hiking checklists to make sure you don’t forget anything important. Here are some notes on how to best use the lists: The Ten Essentials: Items that are part of the Ten Essentials are marked by an asterisk (*). The exact items you take can be tailored to your trip based on considerations such as weather, difficulty, duration and distance from help. To learn more, see our article on the Ten Essentials.These checklists are guidelines. They are deliberately comprehensive; your needs may vary. Adapt them to suit your hike as necessary. Printer-friendly PDFs. Print out the PDF version of each checklist for easy reference while packing. If you’re someone who likes to physically tick items off your list, consider laminating the checklists. Then use a dry erase marker to mark them up. These items should always be on your hiking checklist: Hiking pack,Weather-appropriate clothing (think moisture-wicking and layers),Hiking footwear,Plenty of food,Plenty of water,Navigation tools such as a map and compass,First-aid kit,Knife or multi-tool,The rest of the Ten Essentials as appropriate for your hike",
        "image": couple,
    },
    {
        "id": "123457", "title": "How to Set Up a Tent", "article": "Before you hit the trail, set your tent up at home: Home offers a low-stress environment for you to master the pitching process for a new tent. The worst time for learning is after you’ve finished a long day of hiking, the sun has set and the rain is coming down sideways. Read the instructions carefully and inventory the parts: Reading instructions, rather than grabbing things and winging it, is a great way to prevent confusion and damage to tent parts. And if a piece is missing, you’ve built in the time to get it before your trip. And don’t forget to pack along a copy of the instructions. Decide on your footprint strategy: Though tent floors are heavy duty to stand up to water, abrasion and wear, the ground is a formidable foe. You can combat this problem by buying a footprint—a custom-sized ground sheet that offers an extra layer of protection. You can also buy Tyvek® material to make your own footprint or you can simply buy a tarp. Footprints are sized smaller than your tent floor so they don’t catch and pool rainwater under your tent. If you make your own footprint, do the same. If you bring a full tarp, fold it under so that no part extends beyond the floor perimeter. Clear debris from your tent site: Your goal is to protect the tent floor and remove things that can poke you in the backside. This isn’t an excavation project, though: Pick another site if you feel like yours needs major work.If it’s windy, stake down tent corners: A strong wind can make laying out your tent feel more like flying a kite. Quickly stake down the corners at the outset; it’s a simple task to restake your tent in its final position later. Go slow with the poles: During setup, poles can get tweaked or chipped, so take a few extra moments to unfurl and seat each pole section with care.Stakeout tactics: You'll get maximum holding power in most types of soil if the stake is fully vertical as you drive it into the ground. Leave just enough stake exposed to allow you to slip a tie-down cord over it. If you can't push the stake in with your hand or foot, you can use a large rock for this job; you can also pack a special stake hammer.Pack extra stakes in case some hidden rock pretzels one of yours. Consider packing sand anchors or snow stakes for those environments.", "image": tourists,
    },
    { "id": "12348", "title": "Understanding Sleeping Bag Temperature Ratings", "article": "Because waking up in your tent shivering in the middle of the night is a miserable experience, the key factor when you choose a sleeping bag is its temperature rating. If you have a reasonable idea of the coldest conditions you anticipate on your adventure, you can pick a bag that will keep you warm at or below that temperature.Sleeping bag temperature ratings, however, are a somewhat complicated subject. To understand them better, it helps to understand how the bags are tested for warmth in the lab (including some of the limitations in the process), and the meaning of some not-so-intuitive terms you’ll see in bag temperature ratings. Here are important things to understand when using temperature ratings to shop for a sleeping bag:Lab-tested temperature ratings (as indicated by “EN” or “ISO” ratings) are useful for making an apples-to-apples comparison between sleeping bags from different brands. Real-world comfort probably won’t match lab-tested temperature ratings because of all the variables that a lab can’t simulate. How Sleeping Bags are Tested In the old days, brands tested sleeping bags in their own labs using a variety of methods, so there was no way to know if one company’s 30-degree bag was truly just as warm as another’s 30-degree bag. The bag industry solved this problem by agreeing to test bags the same way for all brands. Today most brands send their sleeping bags to an independent test lab that assigns bag temperature ratings.EN (European Norm), was the original standard adopted by the sleeping bag industry. Today, a new entity, the ISO (International Standards Organization), oversees bag testing, but the method is almost identical to the EN bag test. (Because ISO testing is so similar to EN testing, you can compare your old EN-rated bag to a newer bag that sports an ISO temperature rating when you shop.)", "image": hiking, }

]

export default campingArticles;