import happiness from '../../images/blog/happiness.jpg';
import things from '../../images/blog/things.jpg';
import girls from '../../images/blog/girls.jpg';
import group from '../../images/blog/group.jpg';

const data = [
    {
        "id": "12345",
        "title": "How to Choose Tents for Camping",
        "article": "Car camping with family or friends is a summer pastime for many of us. Whether the campground itself is the main attraction or it's simply your base camp for nearby activities, this article will help you find the right camping tent—your home away from home.Tent Sleeping Capacity When choosing your tent, first choose a model based on your group's size and whether or not you might need additional space for extra friends, gear or dogs. Keep in mind, however, that no industry standard exists that defines per-person tent dimensions. When evaluating tent capacity ratings, our general advice is this: Assume a close fit. If you seek more room, consider upsizing your tent capacity by 1 person, particularly if you or your usual tent companion(s): -are large people -are claustrophobic -toss and turn at night -sleep better with more than average elbow room -are bringing a small child or a dog. Tents Seasonality: 3-Season Tents By far the most popular choice of tents, 3-season tents are lightweight shelters designed for the relatively temperate conditions of spring, summer and fall. They are usually equipped with ample mesh panels to boost air flow. Mesh panels keep out insects (but can still let in powdery blowing sand). Properly pitched with a taut rainfly, 3-season tents can withstand downpours but are not the best choice for sustained exposure to harsh storms, violent winds or heavy snow. The primary functions of 3-season tents: Keep you dry during rain or light snow. Shield you from bugs. Provide privacy. 3- 4-Season Tents Extended-season (3+ season) tents are engineered for prolonged 3-season usage, suitable for summer use but also trips in early spring and late fall when moderate snow may be encountered. Their goal: offer a balance of ventilation, strength and warmth-retention.  Typically they include 1 or 2 more poles and fewer mesh panels than pure 3-season models. This makes them sturdier and warmer than their 3-season cousins. Extended-season tents are a good choice for those who make frequent trips to exposed, high-elevation destinations. While very sturdy, they are not as fully fortified for harsh winter weather as 4-season tents. 4-Season Tents Engineered to withstand fierce winds and substantial snow loads, mountaineering tents can be used in any season. Their chief function, though, is to stand firm in the face of seriously inhospitable weather, principally in winter or above treeline.",
        "image": happiness,
    },
    {
        "id": "123456", "title": "How to Go Camping",
        "article": "If you haven’t been camping since childhood or have never camped out before, we can help. We keep things simple for your first trip, talk a little about tents and sleeping bags, and show you how to build a great campfire. All that, plus we give you a printable checklist full of stuff you might want for future trips.Even if you’re the most urban of creatures, the urge to get out of the city—to camp out, in fact—can seize your imagination at any time. If you find yourself contemplating car camping for the first time, but also find the gear and the prep to be a little daunting, don’t despair. We’re here to help. The ultimate essential for beginner campers is, of course, an experienced outdoorsy person to help you. You can find those folks teaching classes at REI. And if you’re lucky enough to have a friend with a campground reservation and a garage full of gear to share, then simply jump ahead to our handy, printable checklist of camping essentials we’ve provided at the tail end of story. But you can also do this camping thing completely on your own. You just need a few basic pieces of gear and then decide where you’re going. When going car camping for the first time, start with an overnight campout and keep it simple: To save money, borrow or rent big-ticket gear.To maximize your comfort, always bring appropriate clothes for cold and rain. To satisfy your fresh-air-fueled hunger, bring plenty of food. To keep your options open, camp close to home. (There’s no shame in bailing if problems arise.) To ensure you get a good first impression, postpone your campout if the weather forecast is awful. To be sure you leave a good impression for those who come after you, make sure you follow Leave No Trace principles.",
        "image": group,
    },
    { "id": "123457", "title": "Where to Go Camping", "article": "From national parks to RV parks, the possibilities are endless. Humanity’s enthusiasm for camping is also endless, though, so make your campground reservations well in advance. Where Can I Camp goes into detail about places that offer camping and guidelines that apply in those lands. Recreation.gov is an online site that covers public lands campsite reservations nationwide. Hipcamp is a great resource for finding and reserving private lands campsites nationwide (and worldwide).Another option is campgrounds that are open on a first-come, first-served basis. Booking months ahead isn’t required, but it’s a good idea to check with the campground to get tips on the best time to show up in order to snag a site. Unless you want to get in touch with your inner feral animal, avoid dispersed camping (no facilities) and primitive sites (pit toilets). Most first-time campers are more comfortable in a developed campground, so look for one with flush toilets and running water. It’s also worth verifying that you have treated water coming out of a spigot. Natural water sources introduce the added complexity of water treatment to avoid health risks.", "image": girls, },
    { "id": "12348", "title": "Camping Checklist", "article": "Camping is a great way to get outside with family and friends or even by yourself. You can go camping in many state and national parks, at private campgrounds, in the backcountry or even in your own backyard. (For more info, read Where Can I Camp?) Most campsites include a picnic table, a place to park your car and a spot to pitch your tent. Many also have shared bathrooms and running water. Part of the joy of camping is needing very little gear to exist outdoors. But it’s also nice to have a comfortable, convenient and homey campsite. If it’s your first time camping, it might be best to borrow or rent some of these things. As you become a more experienced camper, you may find that part of the fun is figuring out what to bring along to meet your needs. While you’re packing, use this handy camping checklist to make sure you don’t forget anything important and make sure to stock up on the things you need. This is a comprehensive list, and we don't expect you to bring along every item — though we won't judge you if you do!", "image": things, }

]

export default data;